### ISSUE TITLE
current active image list is not correctly resolving the image type

### ISSUE THREAD

**Issue by RZachLamberty** [ElderResearch/gpu_docker#12]
because the images for dev, nogpu_dev, and prod are all identical, the script which is collecting the particular type of image via simple docker commands cannot tell which type was actually selected to launch that image.

for example, if you launched an image of type `eri_nogpu_dev`, the tags assocaited with that image are `['eri_dev:latest', 'eri_nogpu_dev:latest', 'eri_prod:latest']`.

to make the list usable, we need a way to disambiguate them. currently we will always see only `eri_dev:latest` as the tag (and hence a `eri_gpu` type).

**Comment by semperstew** [comment]
Not trying to knock it, but I think that the multiple images/tags were an early optimization. I feel that the best way to solve this would be to disambiguate only within the `launcher.py` image dictionary. That is, users are presented with a selectable list of images in the launch app that only corresponds to the difference in flags passed to `docker run`.

**Comment by RZachLamberty** [comment]
agreed re: multiple images / tags, and especially agree re: tags.

the hard thing is taking a list of currently running containers and attempting to identify which "type" they are. I thought tags was the shortest path and it turns out it's not an option. beyond that, I could either go down the path of inspecting the various flags passed when the container was launched (seems like a bad idea) or proactively indicate that information, either by setting an environment variable I can recapture or naming these containers in some obvious way

complicating all of this is the possibility of supporting the multiple instances of the non-gpu development environment, as they end up stepping on eachother when it comes to simple options (e.g. naming conventions, port numbers)

**Comment by semperstew** [comment]
What if you assign a name to the launched container using the `--name` flag at runtime. Then, the results of `docker ps` can be filtered by container name. Just use a unique name for each image type.

**Comment by RZachLamberty** [comment]
that was what I meant by "naming these containers in some obvious way". that's what I'm leaning towards, but I have to figure out how to make it flexible for the multiple possible non-gpu images

**Comment by semperstew** [comment]
For non-gpu images, it's probably just easiest to name them with the user's name.

**Comment by RZachLamberty** [comment]
can be obtained from `c.attrs['Config']['Image']` rather than `c.image.tags` list.

fixed in commit (a2155d852cc4fe81162be3146cfdd87b716d5a87)[https://github.com/ElderResearch/gpu_docker/commit/a2155d852cc4fe81162be3146cfdd87b716d5a87]
