### ISSUE TITLE
Add text mining libraries to the image(s)

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#13]
We need to include nltk, SpaCy, and gensim in the python environments: 

Justification: Most DNN frameworks do not include fast text mining data prep tools and developers recommend to use one or a combo of the above libraries.

**Comment by RZachLamberty** [comment]
`nltk` is already installed, fwiw

**Comment by oersoy1** [comment]
Thx, I checked the base Python env on the machine and could not find it.   I should have started a container and checked it there.  fwiw, base python now points to 2.7 not 3.5.  Don't know when that switch happened. I remember we changed the ENV variable manually a while back. Regardless, it is not important any more.

**Comment by RZachLamberty** [comment]
`spacy` and `gensim` are now also installed, as of commit [ab86e784ebb89c92802b2c44c038cfd9e41c2928](https://github.com/ElderResearch/gpu_docker/commit/ab86e784ebb89c92802b2c44c038cfd9e41c2928)

fwiw, installing `spacy` takes a surprisingly long time (minutes, not seconds)
