### ISSUE TITLE
Install a new DL framework: MXNET

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#14]
Apache MXNET is highly scalable, has better CPU and Memory utilization and directly written in C++. 

In most benchmarking papers I read, MXNET beats tensorflow, pytorch and caffe2 in terms of performance.  API looks very much like PyTorch. 

https://mxnet.apache.org/

**Comment by RZachLamberty** [comment]
added in commit [67889a611782e26736f3df6a0541ae1835aa2fa8](https://github.com/ElderResearch/gpu_docker/commit/67889a611782e26736f3df6a0541ae1835aa2fa8)
