### ISSUE TITLE
Install ONNX

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#15]
Open Neural Network Exchange (ONNX)  is an important standardization effort that allows models to be exchanged (import/export) between frameworks.  As far as I can tell most developers of frameworks are going in this direction and support the idea. I believe all but Tensorflow support ONNX. 

https://github.com/onnx/onnx

**Comment by RZachLamberty** [comment]
added in commit [121342750639b73d194764f2993409e7477bb044](https://github.com/ElderResearch/gpu_docker/commit/121342750639b73d194764f2993409e7477bb044)
