### ISSUE TITLE
Flask app to create a GPU session allows empty PWDs

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#20]
To duplicate the issue:

1. Enter Devbox user name 
2. Click enter 
GPU session gets created
3. Select the session and click the Kill Session button without a password
GPU session gets deleted.

**Comment by RZachLamberty** [comment]
fixed in ff6c3250254d2ab2d0c8a7042aaecd20804ac1de

**Comment by RZachLamberty** [comment]
fixed in ff6c3250254d2ab2d0c8a7042aaecd20804ac1de
