### ISSUE TITLE
Install Darknet

### ISSUE THREAD

**Issue by tomshafer** [ElderResearch/gpu_docker#30]
The creator of YOLO has a C-based, GPU-capable deep neural network framework called Darknet, available at https://pjreddie.com/darknet/. It would be nice to have on the GPU box to run object detection in addition to PyTorch, Keras, etc. This would likely be directly applicable to Project Iris.

**Comment by RZachLamberty** [comment]
installed via commit d556a86a8609dddc2e1746567500510da3509187

for reference, the test we used to "verify" installation was found here: https://pjreddie.com/darknet/imagenet/
