### ISSUE TITLE
cname for eri-gpu used in href not valid for vpn connetions

### ISSUE THREAD

**Issue by RZachLamberty** [ElderResearch/gpu_docker#33]
I'm not sure if this is a joseph problem or a me problem (as in, what should I expect?)

url eri-gpu:8888 is not valid when connected via vpn, needs the fqdn (eri-gpu.cho.elderresearch.com)

**Comment by jdimeo** [comment]
This happens all the time- not sure how/why/when. I've had to have people do nexus.cho.elderresearch.com for Maven, etc.
