### ISSUE TITLE
Install Python cudatoolkit

### ISSUE THREAD

**Issue by tomshafer** [ElderResearch/gpu_docker#37]
`numba` works fine for CPU. When trying to run an example GPU command, I receive the following:

> NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`: library nvvm not found

**Comment by RZachLamberty** [comment]
my bad, I thought that was installed as part of the tensor flow base image. will try and fix today.

**Comment by RZachLamberty** [comment]
@tomshafer can you suggest a command you ran and an expected behavior?

**Comment by tomshafer** [comment]
I was just looking at [this documentation](http://numba.pydata.org/numba-doc/0.38.0/cuda/kernels.html#kernel-invocation).

Maybe try:

```python
import numpy as np
from numba import cuda

@cuda.jit
def increment_a_2D_array(an_array):
    x, y = cuda.grid(2)
    if x < an_array.shape[0] and y < an_array.shape[1]:
       an_array[x, y] += 1

an_array = np.linspace(0.0, 1.0, 10000).reshape(-1, 100)

threadsperblock = (16, 16)
blockspergrid_x = math.ceil(an_array.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(an_array.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)
increment_a_2D_array[blockspergrid, threadsperblock](an_array)

```

**Comment by RZachLamberty** [comment]
the issue is that we aren't using `conda` to manage the global, single environment in this machine. it's awesome that they have it for general users in shared systems, but pretty irksome that they don't have more detailed instructions on how to actually install the thing...

I did add `libnvvm3` thinking that would do it, but no dice.

will have to investigate

**Comment by RZachLamberty** [comment]
yeah, hold up. the toolkit *is* installed in the base image

```
root@493f8f2a5930:/# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

this is some other problem.

**Comment by RZachLamberty** [comment]
got it https://stackoverflow.com/a/48670746
