### ISSUE TITLE
install topicmodels and gsl for r docker image

### ISSUE THREAD

**Issue by RZachLamberty** [ElderResearch/gpu_docker#43]
being used by lkent for her bench project

**Comment by RZachLamberty** [comment]
lkent provided [this blog post](http://tinyheero.github.io/2016/02/20/install-r-topicmodels.html)

**Comment by RZachLamberty** [comment]
success is `library(topicmodels)`

**Comment by RZachLamberty** [comment]
I actually went with [the ubuntu package](https://launchpad.net/ubuntu/+source/gsl) instead (`libgsl-dev`, for headers). it's maintained by [the one and only](https://launchpad.net/~edd) so I feel it's probably good enough for us.

**Comment by oersoy1** [comment]
thumbs up. were you able to install the topicmodels library?

**Comment by RZachLamberty** [comment]
this is done
