### ISSUE TITLE
Add build-essential and swig packages to image

### ISSUE THREAD

**Issue by trent-b** [ElderResearch/gpu_docker#47]
In order to install SMAC3 (a state-of-the-art hyperparameter optimizer), I need build-essential and swig to be added to the docker image. They have to be installed with apt-get, not pip. See https://automl.github.io/SMAC3/stable/installation.html.

**Comment by semperstew** [comment]
@trent-b `swig`, `build-essential`, and `smac` have been installed. Closing this issue. Please re-open it if you run into problems with the installation.
