### ISSUE TITLE
Install pyodbc on the GPU box containers

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#52]
This is needed so that we can write to the Client Database faster.  User gets a GCC error. 

tbradberry@6016a8c58149:~/repos/ltv$ pip install --user pyodbc
Collecting pyodbc
 Using cached https://files.pythonhosted.org/packages/0f/aa/733a4326bfdef7deff954aa109ded6acf29d802a91fd87eedf6fc46fd91c/pyodbc-4.0.25.tar.gz
Building wheels for collected packages: pyodbc
 Building wheel for pyodbc (setup.py) ... error
 Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_c1h_l1r/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-rnpp1ziq --python-tag cp35:
 running bdist_wheel
 running build
 running build_ext
 building 'pyodbc' extension
 creating build
 creating build/temp.linux-x86_64-3.5
 creating build/temp.linux-x86_64-3.5/src
 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.25 -I/usr/include/python3.5m -c src/buffer.cpp -o build/temp.linux-x86_64-3.5/src/buffer.o -Wno-write-strings
 cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
 In file included from src/buffer.cpp:12:0:
 src/pyodbc.h:56:17: fatal error: sql.h: No such file or directory
 compilation terminated.
 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

 ----------------------------------------
 Failed building wheel for pyodbc
 Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
 Running setup.py install for pyodbc ... error
   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_c1h_l1r/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-nl__x2ob/install-record.txt --single-version-externally-managed --compile --user --prefix=:
   running install
   running build
   running build_ext
   building 'pyodbc' extension
   creating build
   creating build/temp.linux-x86_64-3.5
   creating build/temp.linux-x86_64-3.5/src
   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.25 -I/usr/include/python3.5m -c src/buffer.cpp -o build/temp.linux-x86_64-3.5/src/buffer.o -Wno-write-strings
   cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
   In file included from src/buffer.cpp:12:0:
   src/pyodbc.h:56:17: fatal error: sql.h: No such file or directory
   compilation terminated.
   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

   ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_c1h_l1r/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-nl__x2ob/install-record.txt

**Comment by trimyjer** [comment]
@semperstew - we might be able to solve this error by installed `python3-dev`: https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

**Comment by trimyjer** [comment]
Scratch that - I launched the `eri-python` docker image and ran `apt-get install unixodbc-dev` and then `pip install pyodbc` worked!
https://github.com/mkleehammer/pyodbc/issues/276

**Comment by semperstew** [comment]
closing per e4dedd4

**Comment by oersoy1** [comment]
This has not been resolved.  We are getting basically this same error 

https://stackoverflow.com/questions/44527452/cant-open-lib-odbc-driver-13-for-sql-server-sym-linking-issue

It appears like MS SQL ODBC drivers are not installed on the container.

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

FYI.. I have installed them on the root machine because we needed it ASAP but has not worked.
