### ISSUE TITLE
Update Python to 3.7

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#55]
Containers have 3.5 

Title says it all.

**Comment by semperstew** [comment]
The base image from which all of our images derive is `tensorflow/tensorflow:[version]-gpu-py3`. Our only choices of python version are 2.7 or 3.5. As it stands, the only way to upgrade to python3.7 is to hand-roll a tensorflow base image with 3.7 installed. I don't know about you, but that's not really something that I care to maintain in the long run. 
Are there particular features of python3.7 that you can't live without?

**Comment by oersoy1** [comment]
Nah..  I had to refactor some of my code for str formatting type of stuff..  Tensorflow.. Yuck..

**Comment by oersoy1** [comment]
Pytorch works with 3.7 and 3.6 and 3.5

**Comment by semperstew** [comment]
TF certainly works with 3.7, but they aren't shipping a prebuilt TF image with 3.7 installed (yet).

**Comment by semperstew** [comment]
Closing. Won't fix at this time.
