### ISSUE TITLE
Install libicu-dev

### ISSUE THREAD

**Issue by trent-b** [ElderResearch/gpu_docker#63]
I am trying to pip install polyglot. One of the dependencies is pyicu. When I try to pip install pyicu, I get the following error:

 RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.

According to SO, doing a `sudo apt install libicu-dev` may resolve this problem.

**Comment by oersoy1** [comment]
I installed it on the bare machine..  Needs to be installed on the Docker image, most likely.

**Comment by trent-b** [comment]
I get the same error, so I agree that libicu-dev most likely needs to be installed on the Docker image.
