### ISSUE TITLE
On the Chill container, importing pymc3 leads to a warning

### ISSUE THREAD

**Issue by trent-b** [ElderResearch/gpu_docker#72]
On the Chill container, `import pymc3` leads to the following warning:
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

The warning means that pymc3 will run slower.

Please install the following on the Chill container, and I will test the import of pymc3 again:
`sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran`

**Comment by enmyj** [comment]
@trent-b - I installed the packages into the chill image, try launching a new one and let me know if it didn't work.

**Comment by trent-b** [comment]
That worked. I no longer receive the warning message. Thanks!
