### ISSUE TITLE
On the Chill container, error when using graphviz

### ISSUE THREAD

**Issue by trent-b** [ElderResearch/gpu_docker#73]
When I use `graphviz` to try to visualize a PyMC3 model, I get the following error:
failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

Apparently this is fixed by installing the following:
`sudo apt-get install graphviz`

Please install, and I can test again.

**Comment by enmyj** [comment]
@trent-b - I installed the packages into the chill image, try launching a new one and let me know if it didn't work.

**Comment by trent-b** [comment]
That worked. I can call a function that uses graphviz now. Thanks!
