### ISSUE TITLE
install bc (basic calculator) tool

### ISSUE THREAD

**Issue by salml** [ElderResearch/gpu_docker#83]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
`bash: bc: command not found`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**.
```
COPY AND PASTE OFFENDING CODE HERE
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Need `bc` to run a shell script for a baseline model on a bench task

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
COPY AND PASTE STACKTRACES HERE
```

**Comment by enmyj** [comment]
This is addressed by #85
