### ISSUE TITLE
Emacs on the Python Docker Image

### ISSUE THREAD

**Issue by geomex** [ElderResearch/gpu_docker#84]
* **Do you want to request a *feature* or report a *bug*?**

Requesting Emacs to be added to the docker image. 

* **What is the current behavior?**

No emacs. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**.
```
COPY AND PASTE OFFENDING CODE HERE
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
COPY AND PASTE STACKTRACES HERE
```

**Comment by enmyj** [comment]
closed per conversation in #86
