### ISSUE TITLE
install git-lfs for Python container

### ISSUE THREAD

**Issue by trent-b** [ElderResearch/gpu_docker#88]
According to https://github.com/ProsusAI/finBERT, git-lfs should be installed before I clone FinBERT. Could git-lfs please be installed as described at https://help.github.com/en/github/managing-large-files/installing-git-large-file-storage?

**Comment by enmyj** [comment]
@trent-b - I installed git-lfs onto the Box itself, so you should be able to do this using `git` via `ssh` directly to the box in the future. Does that work? Otherwise, I can add it into the containers for the future.

**Comment by trent-b** [comment]
After adding to the containers, everything looks good!
