### ISSUE TITLE
Change default shell to bash

### ISSUE THREAD

**Issue by semperstew** [ElderResearch/gpu_docker#9]
The default shell is currently `sh` for all users. Change the default shell to `bash`.

**Comment by RZachLamberty** [comment]
what was it that surface this? what was the behavior that you saw that was not preferable? my guess is that the terminal launched by `jupyter` was not what was expected.

I think I've fixed this but don't know what test case I should be verifying against

**Comment by RZachLamberty** [comment]
fixed as of commit [3695a09eee86b0f8f764a4977751c8afed34473c](https://github.com/ElderResearch/gpu_docker/commit/3695a09eee86b0f8f764a4977751c8afed34473c)

**Comment by RZachLamberty** [comment]
I'll hold this open for now just to make sure I've done this correctly

**Comment by semperstew** [comment]
The default shell launched `jupyter` was `sh`. Wanted to change it to `bash` for more user-friendly interaction since most people are used to the niceties that `bash` offers.
